export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const HOME_REQUEST = "HOME_REQUEST";
export const HOME_SUCCESS = "HOME_SUCCESS";
export const HOME_FAILED = "HOME_FAILED";

export const CHANNEL_REQUEST = "CHANNEL_REQUEST";
export const CHANNEL_SUCCESS = "CHANNEL_SUCCESS";
export const CHANNEL_FAILED = "CHANNEL_FAILED";

export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";