export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const HOME_REQUEST = "HOME_REQUEST";
export const HOME_SUCCESS = "HOME_SUCCESS";
export const HOME_FAILED = "HOME_FAILED";

export const CHANNEL_REQUEST = "CHANNEL_REQUEST";
export const CHANNEL_SUCCESS = "CHANNEL_SUCCESS";
export const CHANNEL_FAILED = "CHANNEL_FAILED";

export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAILED = "COMMENT_FAILED";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";

export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";

export const RELATED_VIDEO_REQUEST = "RELATED_VIDEO_REQUEST";
export const RELATED_VIDEO_SUCCESS = "RELATED_VIDEO_SUCCESS";
export const RELATED_VIDEO_FAIL = "RELATED_VIDEO_FAIL";

export const SEARCHED_VIDEO_REQUEST = "SEARCHED_VIDEO_REQUEST";
export const SEARCHED_VIDEO_SUCCESS = "SEARCHED_VIDEO_SUCCESS";
export const SEARCHED_VIDEO_FAIL = "SEARCHED_VIDEO_FAIL";

export const SUBSCRIPTIONS_CHANNEL_REQUEST = "SUBSCRIPTIONS_CHANNEL_REQUEST";
export const SUBSCRIPTIONS_CHANNEL_SUCCESS = "SUBSCRIPTIONS_CHANNEL_SUCCESS";
export const SUBSCRIPTIONS_CHANNEL_FAIL = "SUBSCRIPTIONS_CHANNEL_FAIL";

export const CHANNEL_VIDEOS_REQUEST = "CHANNEL_VIDEOS_REQUEST";
export const CHANNEL_VIDEOS_SUCCESS = "CHANNEL_VIDEOS_SUCCESS";
export const CHANNEL_VIDEOS_FAIL = "CHANNEL_VIDEOS_FAIL";

export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL";

export const GET_LIKED_VIDEO = "GET_LIKED_VIDEO";
export const GET_LIKED_VIDEO_FAIL = "GET_LIKED_VIDEO_FAIL";

export const GET_ALL_LIKED_VIDEO_SUCCESS = "GET_ALL_LIKED_VIDEO_SUCCESS";
export const GET_ALL_LIKED_VIDEO_REQUEST = "GET_ALL_LIKED_VIDEO_REQUEST";
export const GET_ALL_LIKED_VIDEO_FAIL = "GET_ALL_LIKED_VIDEO_FAIL";

export const ADDING_RATE_SUCCESS = "ADDING_RATE_SUCCESS";
export const ADDING_RATE_FAIL = "ADDING_RATE_FAIL";

export const PLAYLIST_VIDEOS_REQUEST = "PLAYLIST_VIDEOS_REQUEST";
export const PLAYLIST_VIDEOS_SUCCESS = "PLAYLIST_VIDEOS_SUCCESS";
export const PLAYLIST_VIDEOS_FAIL = "PLAYLIST_VIDEOS_FAIL";
export const PLAYLIST_ALL_VIDEOS_SUCCESS = "PLAYLIST_ALL_VIDEOS_SUCCESS";
